### PR TITLE
vcsim: resolve issue making device changes on clone (resolves #1355)

### LINKED ISSUE #1355: vcsim: Setting manual mac address on VM Clone
I'm trying to fix an issue in the Ansible module where you're unable to set a manual mac address on an already present network interface when cloning a VM. Got everything working fine when running against our live vSphere 6.5, but the Ansible test is failing due to vcsim not applying these changes.

In the background, the following SOAP body is sent for cloning:
```xml
    <?xml
        version="1.0"
        encoding="UTF-8"
        ?>
    <soapenv:Envelope
        xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <soapenv:Body>
            <CloneVM_Task
                xmlns="urn:vim25">
                <_this
                    type="VirtualMachine">
                    vm-66
                    </_this>
                <folder
                    type="Folder">
                    folder-3
                    </folder>
                <name>
                    nictest00
                    </name>
                <spec>
                    <location>
                        <datastore
                            type="Datastore">
                            /tmp/govcsim-DC0-LocalDS_0-966032278@folder-5
                            </datastore>
                        <pool
                            type="ResourcePool">
                            resgroup-20
                            </pool>
                        </location>
                    <template>
                        false
                        </template>
                    <config>
                        <deviceChange>
                            <operation>
                                edit
                                </operation>
                            <device
                                xsi:type="VirtualVmxnet3">
                                <key>
                                    202
                                    </key>
                                <deviceInfo>
                                    <label>
                                        Network Adapter 1
                                        </label>
                                    <summary>
                                        VM Network
                                        </summary>
                                    </deviceInfo>
                                <backing
                                    xsi:type="VirtualEthernetCardNetworkBackingInfo">
                                    <deviceName>
                                        VM Network
                                        </deviceName>
                                    <network
                                        type="Network">
                                        network-7
                                        </network>
                                    </backing>
                                <connectable>
                                    <startConnected>
                                        true
                                        </startConnected>
                                    <allowGuestControl>
                                        true
                                        </allowGuestControl>
                                    <connected>
                                        true
                                        </connected>
                                    </connectable>
                                <controllerKey>
                                    100
                                    </controllerKey>
                                <unitNumber>
                                    1
                                    </unitNumber>
                                <addressType>
                                    manual
                                    </addressType>
                                <macAddress>
                                    aa:bb:cc:dd:aa:dd
                                    </macAddress>
                                <wakeOnLanEnabled>
                                    true
                                    </wakeOnLanEnabled>
                                </device>
                            </deviceChange>
                        </config>
                    <powerOn>
                        false
                        </powerOn>
                    </spec>
                </CloneVM_Task>
            </soapenv:Body>
        </soapenv:Envelope>
```

Basically the same request on a live vSphere works fine - the mac address is changed and everyone is happy. On the vcsim, however, the mac address on the new VM is still generated (00:0c:29:8e:f6:af) instead of the manual one requested.

### PR DESCRIPTION
**Pull request by zeot**
use `Config.DeviceChange` instead of `Location.DeviceChanges` as parameter for device configuration on VM clone. This resolves #1355

### CODE REVIEW

**Comment by zeot** [comment]
Hm. Tests are failing but "manual testing" is successful (the mac address is changed, and everything goes though). Anyone with better insight in the project know what the problem here is?

Maybe there is a difference in the XML sent by pyvmomi and govc.
I'll keep digging

File: simulator/virtual_machine.go [hunk 1]
```diff
@@ -1475,7 +1475,7 @@ func (vm *VirtualMachine) CloneVMTask(ctx *Context, req *types.CloneVM_Task) soa
 
 		ref := ctask.Info.Result.(types.ManagedObjectReference)
 		clone := Map.Get(ref).(*VirtualMachine)
-		clone.configureDevices(&types.VirtualMachineConfigSpec{DeviceChange: req.Spec.Location.DeviceChange})
+		clone.configureDevices(&types.VirtualMachineConfigSpec{DeviceChange: req.Spec.Config.DeviceChange})
```
Comment (dougm) [inline simulator/virtual_machine.go]: Note that you'll need to check `if req.Spec.Config != nil` as it is an optional field.

Comment (zeot) [reply simulator/virtual_machine.go]: Applied this change. All tests pass now on my local machine, and setting mac address on clone from pyvmomi works as well.

Thank you!
