### PR TITLE
vcsim: add session support

### LINKED ISSUE #923: vcsim: PropertyFilters not destroyed when Session is closed
PropertyFilters are not being destroyed when user terminates the session (e.g. login, logout).

**Steps to reproduce:**
1) Login
2) CreateFilter
3) Call WaitForUpdatesEx with empty version (returns a set of filters that user created)
4) Logout
5) Login
6) CreateFilter
7) Call WaitForUpdatesEx with empty version

**Results**
Executing these steps on vcsim server, second WaitForUpdatesEx returns UpdateSet containing 2 filters

**Expected Results**
Executing these steps on real VCenter, second WaitForUpdatesEx returns UpdateSet containing 1 filter

### PR DESCRIPTION
**Pull request by dougm**
Sessions are now tracked across requests, supporting per-session managed objects such as
PropertyCollector, PropertyFilter, ContainerView and the SessionManager itself.

Adds TerminateSession() support and includes proper support for Logout()

Fixes #923

### CODE REVIEW

File: simulator/session_manager.go [hunk 1]
```diff
@@ -61,16 +72,35 @@ func (s *SessionManager) Login(login *types.Login) soap.HasFault {
...
+	s.remove(ctx.Session.Key)
 	return &methods.LogoutBody{Res: new(types.LogoutResponse)}
 }
 
+func (s *SessionManager) TerminateSession(ctx *Context, req *types.TerminateSession) soap.HasFault {
+	for _, id := range req.SessionId {
+		if id == ctx.Session.Key {
+			return &methods.TerminateSessionBody{Fault_: Fault("", &types.InvalidArgument{})}
+		}
+		s.remove(id)
```
Comment (anfernee) [inline simulator/session_manager.go]: do we want to check first then remove to avoid removing half of the sessions?

Comment (dougm) [reply simulator/session_manager.go]: Real ESX/VC actually behaves the same way as this.
