### PR TITLE
api: add Content Library update session file APIs

### LINKED ISSUE #3258: [BUG] Some operations are missing in the Content Library update session file API
**Describe the bug**
Some operations are missing in the Content Library update session file API.

**To Reproduce**

In this [library_item_updatesession_file.go](https://github.com/vmware/govmomi/blob/main/vapi/library/library_item_updatesession_file.go), a couple of operations that are available on [vSphere API](https://developer.vmware.com/apis/vsphere-automation/latest/content/library/item.updatesession.file/) are missing here:
- list
- remove
- validate
- probe (not released yet but available for a while now)

**Expected behavior**
Expect the above operations to be available in the [library_item_updatesession_file.go](https://github.com/vmware/govmomi/blob/main/vapi/library/library_item_updatesession_file.go) in order to leverage govmomi for content library integration work in Golang.

**Affected version**
Most of the above operations are available since vSphere 6.0, with the exception of probe API not released yet.

### PR DESCRIPTION
**Pull request by dougm**
Closes #3258

### CODE REVIEW

File: govc/library/probe.go [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+
+	f.BoolVar(&cmd.fail, "f", false, "Fail if probe status is not success")
+}
+
+func (cmd *probe) Usage() string {
+	return "URI"
+}
+
+func (cmd *probe) Description() string {
+	return `Probe source endpoint.
```
Comment (ericvmw) [inline govc/library/probe.go:58]: nit: Probe remote HTTPS endpoint.

File: govc/library/probe.go [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+
+Examples:
+  govc library.probe http://example.com/file.ova`
```
Comment (ericvmw) [inline govc/library/probe.go:61]: nit: use https:// instead of http://

File: govc/library/probe.go [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+
+type probeResult struct {
+	*library.ProbeResult
+}
+
+func (r *probeResult) Write(w io.Writer) error {
+	tw := tabwriter.NewWriter(w, 2, 0, 2, ' ', 0)
+
+	fmt.Fprintf(tw, "Status:\t%s\n", r.Status)
+	thumbprint := r.SSLThumbprint
```
Comment (ericvmw) [inline govc/library/probe.go:72]: Just a note: a new field for the full SSL certificate is being added to the ProbeResult, and will be released soon.

File: govc/library/session/ls.go [hunk 4]
```diff
@@ -102,26 +107,45 @@ func (cmd *ls) Run(ctx context.Context, f *flag.FlagSet) error {
...
 			item, err := m.GetLibraryItem(ctx, session.LibraryItemID)
-			if err != nil {
-				return err
+			if err == nil {
+				// can only show library path if item exists
+				lib, err := m.GetLibraryByID(ctx, item.LibraryID)
+				if err != nil {
+					return err
+				}
+				session.LibraryItemID = fmt.Sprintf("/%s/%s", lib.Name, item.Name)
```
Comment (ericvmw) [inline govc/library/session/ls.go:127]: Curious:
why use lib name and item name as the libraryItemID instead of the real UUID of the item? I'm not familiar with the API code here, I guess this is following some existing pattern in govmomi?

File: vapi/library/library_item_updatesession_file.go [hunk 5]
```diff
@@ -66,24 +73,31 @@ func (c *Manager) AddLibraryItemFile(ctx context.Context, sessionID string, upda
 }
 
 // AddLibraryItemFileFromURI adds a file from a remote URI.
```
Comment (ericvmw) [inline vapi/library/library_item_updatesession_file.go:75]: nit: adds a file from a remote URI to the update session and completes the update session.

File: govc/library/session/ls.go (hunk 4 above)
Comment (dougm) [reply govc/library/session/ls.go:127]: In general govc uses human-readable names rather than IDs where possible. Such as using name or inventory path rather than MOID. And in the case of content library, we also support a [named path](https://github.com/vmware/govmomi/blob/main/vapi/library/finder/README.md)
But it is also possible to use the ID instead if needed.

File: govc/library/probe.go (hunk 3 above)
Comment (dougm) [reply govc/library/probe.go:72]: ack. `ProbeResult` includes an `SSLCertificate` field that'll be included with the `-json` output.

File: govc/library/probe.go (hunk 1 above)
Comment (dougm) [reply govc/library/probe.go:58]: http is also supported, but will qualify that with the 2 supported schemes. Also note this library.probe command is currently disabled by default, enabled with env `GOVC_SHOW_UNRELEASED=true`.

File: vapi/library/library_item_updatesession_file.go (hunk 5 above)
Comment (dougm) [reply vapi/library/library_item_updatesession_file.go:75]: Added. I don't remember why we're calling `CompleteLibraryItemUpdateSession` within this method - we could remove that call. I checked GitHub (and bora), don't see any references to the `AddLibraryItemFileFromURI` method outside of govc. What do you think?

File: govc/library/session/ls.go (hunk 4 above)
Comment (ericvmw) [reply govc/library/session/ls.go:127]: I see. It's just a little confusing when I see the field name indicate an ID, I guess it's fine as long as users can navigate objects following this pattern, i.e. able to find the library item given an update session ID.

File: vapi/library/library_item_updatesession_file.go (hunk 5 above)
Comment (ericvmw) [reply vapi/library/library_item_updatesession_file.go]: Thanks! I guess it tries to provide a convenient wrap interface that can finish the file import within one call, though the name may not indicate that clearly, I think it's better to provide consistent interfaces, if this is not a pattern we typically expose APIs in govmomi, it makes sense to decouple completeUpdateSession.

File: vapi/simulator/simulator.go [hunk 6]
```diff
@@ -1443,6 +1524,10 @@ func (s *handler) libraryItemUpdateSessionFileID(w http.ResponseWriter, r *http.
 		}
 		OK(w, ids)
 	case "remove":
+		if up.State != "ACTIVE" {
+			s.error(w, fmt.Errorf("removeFile not allowed in state %s", up.State))
+			return
+		}
 		delete(s.Update, id)
 		OK(w)
 	case "validate":
```
Comment (ericvmw) [inline vapi/simulator/simulator.go:1533]: `validate` impl would be also needed for complete match of the [vSphere API](https://developer.vmware.com/apis/vsphere-automation/latest/content/api/content/library/item/update-session/update_session_id/fileactionvalidate/post/).

File: govc/library/session/ls.go (hunk 4 above)
Comment (dougm) [reply govc/library/session/ls.go]: That was just re-using an existing type + field. Updated to use a helper type, so `LibraryItemID` is left as-is as you can see with the `-json` output.

File: vapi/library/library_item_updatesession_file.go (hunk 5 above)
Comment (dougm) [reply vapi/library/library_item_updatesession_file.go:75]: Agree it's better to decouple here, done.

File: vapi/simulator/simulator.go (hunk 6 above)
Comment (dougm) [reply vapi/simulator/simulator.go:1533]: Ah I missed validate listed in the issue. I will add that, may not be till tomorrow though.

Comment (dougm) [reply vapi/simulator/simulator.go:1533]: Added client side API for validate. vcsim side still doesn't do any validation of files, but at least returns a response body now (`{has_errors=false}`). I can still add that, but client-side is ready to use

Comment (ericvmw) [reply vapi/simulator/simulator.go:1533]: Cool, thanks!

**Review by ericvmw — APPROVED** [review]
Thanks for adding the support!

**Comment by dougm** [comment]
Thanks @ericvmw !
