### PR TITLE
govc: add json support to find command

### LINKED ISSUE #826: json output does not work with "govc find"
It seems that the json output is not implemented for the "find" function.
The help command says that the json output option is available:

./govc find --help
Usage: ./govc find [OPTIONS] [ROOT] [KEY VAL]...
[...]
Options:
  -cert=                          Certificate [GOVC_CERTIFICATE]
[...]
  -json=false                     Enable JSON output

But it doesn't work.

### PR DESCRIPTION
**Pull request by dougm**
Fixes #826

### CODE REVIEW

File: govc/object/find.go [hunk 1]
```diff
@@ -172,6 +173,19 @@ func (cmd *find) rootMatch(ctx context.Context, root object.Reference, client *v
 	return content != nil
 }
 
+type findResult []string
+
+func (r findResult) Write(w io.Writer) error {
+	for i := range r {
+		fmt.Println(r[i])
```
Comment (anfernee) [inline govc/object/find.go]: write it to `w`?

Comment (dougm) [reply govc/object/find.go]: yes, done.
