### PR TITLE
govc: include sub task fault messages on failure

### LINKED ISSUE #2181: govc should print the fill error stack when commands fail
I ran the following command:

```
$ govc vm.clone -template=true -dc=/remote-site-1 -ds=/remote-site-1/datastore/vsanDatastore -vm=/datacenter/vm/photon-3-kube-v1.19.1 -pool=/remote-site-1/host/cluster/Resources -on=false  photon-3-kube-v1.19.1
[16-11-20 15:39:20] Cloning /datacenter/vm/photon-3-kube-v1.19.1 to photon-3-kube-v1.19.1...Error: Cannot complete file creation operation.
govc: Cannot complete file creation operation.
```

The full error as shown in the vCenter UI is:
```
Clone virtual machine
Status: Cannot complete file creation operation.
Initiator: VSPHERE.LOCAL\Administrator
Target: photon-3-kube-v1.19.1
Server: foo.example.com
Error stack:
    -> There are currently 2 usable fault domains. The operation requires 1 more usable fault domains.
    -> Failed to create object.
```

It would be pretty informative for govc to show the full error stack when an operation fails.

### PR DESCRIPTION
**Pull request by dougm**
Fixes #2181

### CODE REVIEW

File: govc/flags/output.go [hunk 1]
```diff
@@ -195,8 +197,41 @@ type errorOutput struct {
...
+		}
+	}
+
+	messages = append(messages, reason)
+
+	for _, message := range messages {
+		_, ferr := fmt.Fprintf(w, "%s: %s\n", os.Args[0], message)
+		if ferr != nil {
+			return ferr
+		}
```
Comment (jpeach) [inline govc/flags/output.go:231]:
```suggestion
                if _, err := fmt.Fprintf(w, "%s: %s\n", os.Args[0], message); err != nil {
                        return err
                }
```

**Review by jpeach — APPROVED** [review]
