### PR TITLE
vcsim: VirtualDisk file backing datastore is optional

### LINKED ISSUE #871: vcsim: runtime error: invalid memory address or nil pointer dereference
```
2017/10/11 17:50:57 http: panic serving 172.17.0.1:55438: runtime error: invalid memory address or nil pointer dereference
goroutine 213 [running]:
net/http.(*conn).serve.func1(0xc42009ba40)
	/usr/lib/golang/src/net/http/server.go:1721 +0xd0
panic(0xc07bc0, 0x1388010)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
github.com/vmware/govmomi/simulator.(*VirtualMachine).configureDevice(0xc42007d800, 0xc4204de300, 0x9, 0x10, 0x135dca0, 0xc4200a8a50, 0x9, 0x10)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/virtual_machine.go:350 +0x5ac
github.com/vmware/govmomi/simulator.(*VirtualMachine).configureDevices(0xc42007d800, 0xc4205383a0, 0x1, 0x1)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/virtual_machine.go:433 +0x2c5
github.com/vmware/govmomi/simulator.(*VirtualMachine).create(0xc42007d800, 0xc4205383a0, 0xc4201be300, 0x1361aa0, 0xc4201be3c0)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/virtual_machine.go:261 +0x3dd
github.com/vmware/govmomi/simulator.(*createVM).Run(0xc420546f00, 0xc420480680, 0xc4202bb3e8, 0x4ce442, 0x59de5a01, 0xc415853d9b)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/folder.go:265 +0x16e
github.com/vmware/govmomi/simulator.(TaskRunner).Run-fm(0xc420480680, 0xc415853d9b, 0x13a2980, 0x20, 0xc420546fe0)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/task.go:42 +0x39
github.com/vmware/govmomi/simulator.(*Task).Run(0xc420480680)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/task.go:85 +0xf6
github.com/vmware/govmomi/simulator.(*Folder).CreateVMTask(0xc4201ac820, 0xc420538380, 0x0, 0x0)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/folder.go:299 +0x143
reflect.Value.call(0xda1c00, 0xc4201ac820, 0x1a13, 0xdc7c07, 0x4, 0xc4202bba70, 0x1, 0x1, 0xda1c00, 0xb6ad00, ...)
	/usr/lib/golang/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xda1c00, 0xc4201ac820, 0x1a13, 0xc4202bba70, 0x1, 0x1, 0xc4201ac820, 0x1a13, 0xc4203408a0)
	/usr/lib/golang/src/reflect/value.go:302 +0xa4
github.com/vmware/govmomi/simulator.(*Service).call(0xc4200ce900, 0xc4203cbd80, 0xe00, 0xc4203cbd80)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/simulator.go:144 +0x312
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc4200ce900, 0x1363d20, 0xc4201f6700, 0xc4204de000)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/simulator.go:261 +0xbc4
github.com/vmware/govmomi/simulator.(*Service).ServeSDK-fm(0x1363d20, 0xc4201f6700, 0xc4204de000)
	/opt/gocode/src/github.com/vmware/govmomi/simulator/simulator.go:389 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420255ce0, 0x1363d20, 0xc4201f6700, 0xc4204de000)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420266840, 0x1363d20, 0xc4201f6700, 0xc4204de000)
	/usr/lib/golang/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200a88f0, 0x1363d20, 0xc4201f6700, 0xc4204de000)
	/usr/lib/golang/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42009ba40, 0x13643a0, 0xc4204fc740)
	/usr/lib/golang/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2668 +0x2ce
```

### PR DESCRIPTION
**Pull request by dougm**
Issue #868 added default behavior for the VirtualDisk backing FileName,
but left the assumption that the Datastore field was also set.

Also remove a few go lint/vet warnings.

Fixes #871

### CODE REVIEW

File: simulator/virtual_machine.go [hunk 1]
```diff
@@ -404,8 +407,8 @@ func (vm *VirtualMachine) genVmdkPath() (string, types.BaseMethodFault) {
 			}
 		}
 
-		f.Close()
-		os.Remove(f.Name())
+		_ = f.Close()
+		_ = os.Remove(f.Name())
```
Comment (anfernee) [inline simulator/virtual_machine.go]: Just curious, what is the benefit assign return value to `_` here?

Comment (dougm) [reply simulator/virtual_machine.go]: It surpresses warnings from the go 'errcheck' program. Normally you should check/propagate errors
