### PR TITLE
Fix issue 242

### LINKED ISSUE #242: Get "SystemError" at vim25.mo.LoadRetrievePropertiesResponse()
I can not get a suitable virtual machine list with finder.VirtualMachineList() in case that there are some VM templates at VMFolder. A result that o.MissingSet at objectContentToType() returns "environmentBrowser" value at VM template object may be the reason for the error.

https://github.com/vmware/govmomi/blob/master/vim25/mo/retrieve.go#L35

### PR DESCRIPTION
**Pull request by pietern**
This fixes #242.

Thanks to @tkak to investigation and initial patch.

Instead of only merging the fix, I wanted to add an integration test as well so that we can catch regressions. The `functional` package is the place to add more integration tests as needed.

### CODE REVIEW

**Comment by dougm** [comment]
LGTM.  Great to have some more functional tests/helpers that don't depend on govc/bats.

File: test/functional/helper.go [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+		c:   test.NewAuthenticatedClient(t),
+		fns: make([]func(), 0),
+	}
+
+	h.f = find.NewFinder(h.c, true)
+
+	return h
+}
+
+func (h *Helper) Defer(fn func()) {
```
Comment (dougm) [inline test/functional/helper.go]: Don't see this used anywhere, do we need it and Teardown() vs built-in defer?

Comment (pietern) [inline test/functional/helper.go]: I added it so that resources that are added on-demand from the helper code can be cleaned up as well. Without a teardown function it is not possible to capture those in the scope of the test function. I didn't end up using this in the single test case but think it would be good to leave them in for future stuff. For example: if we want to create a resource pool on demand for every test, we should just do that from the helper, but still destroy it after every test run.

**Comment by tkak** [comment]
@pietern Thank you for the modification!

**Comment by pietern** [comment]
@tkak Thank you for figuring out the source of this bug :)
